### ISSUE TITLE
set up wayback machine for the liveweb proxy

### ISSUE THREAD

**Issue by sergeospb** [internetarchive/liveweb#45]
Sorry for this issue, because it is just issue of documentation. I spend a few days for searching, I have just one question - "How I can set up wayback for using this proxy?".

**Comment by anandology** [comment]
This only implements the liveweb proxy part of the wayback machine. However, there is a simple implementation of wayback machine that is available along with liveweb proxy. See Makefile to know how to run wayback machine.

**Comment by sergeospb** [comment]
Understood, thank you very much!
